# Fall 2024 Data Science Track: Week 2 - Data Cleaning Exercise

## Packages, Packages, Packages!

Import *all* the things here! You need the standard stuff: `pandas` and `numpy`.

If you got more stuff you want to use, add them here too. 🙂

In [1]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/python/3.12.1/lib/python3.12/site-packages (3.0.5)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [3]:
# Import here.
import pandas as pd
import numpy as np

## Introduction

With the packages out of the way, now you will be working with the following data sets:

* `food_coded.csv`: [Food choices](https://www.kaggle.com/datasets/borapajo/food-choices?select=food_coded.csv) from Kaggle
* `Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv`: [Ask A Manager Salary Survey 2021 (Responses)](https://docs.google.com/spreadsheets/d/1IPS5dBSGtwYVbjsfbaMCYIWnOuRmJcbequohNxCyGVw/view?&gid=1625408792) as *Tab Separated Values (.tsv)* from Google Docs

Each one poses different challenges. But you’ll―of course―overcome them with what you learned in class! 😉

## Food Choices Data Set

### Load the Data

In [171]:
# Load the Food choices data set into a variable (e.g., df_food).

food_data_set_path = '../data/food_coded.csv'

df_food = pd.read_csv(food_data_set_path)

### Explore the Data

How much data did you just load?

In [172]:
# Count by hand. (lol kidding)
len(df_food)

125

What are the columns and their types in this data set?

In [173]:
# Show the column names and their types.
df_food.info()

<class 'pandas.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   GPA                           123 non-null    str
 1   Gender                        125 non-null    int64
 2   breakfast                     125 non-null    int64
 3   calories_chicken              125 non-null    int64
 4   calories_day                  106 non-null    float64
 5   calories_scone                124 non-null    float64
 6   coffee                        125 non-null    int64
 7   comfort_food                  124 non-null    str
 8   comfort_food_reasons          123 non-null    str
 9   comfort_food_reasons_coded    106 non-null    float64
 10  cook                          122 non-null    float64
 11  comfort_food_reasons_coded.1  125 non-null    int64
 12  cuisine                       108 non-null    float64
 13  diet_current                  124 non-null    str
 14  diet_current_coded            125 non-null    int64
 15  drink                         123 non-null    float64
 16  eating_changes                122 non-null    str
 17  eating_changes_coded          125 non-null    int64
 18  eating_changes_coded1         125 non-null    int64
 19  eating_out                    125 non-null    int64
 20  employment                    116 non-null    float64
 21  ethnic_food                   125 non-null    int64
 22  exercise                      112 non-null    float64
 23  father_education              124 non-null    float64
 24  father_profession             122 non-null    str
 25  fav_cuisine                   123 non-null    str
 26  fav_cuisine_coded             125 non-null    int64
 27  fav_food                      123 non-null    float64
 28  food_childhood                124 non-null    str
 29  fries                         125 non-null    int64
 30  fruit_day                     125 non-null    int64
 31  grade_level                   125 non-null    int64
 32  greek_food                    125 non-null    int64
 33  healthy_feeling               125 non-null    int64
 34  healthy_meal                  124 non-null    str
 35  ideal_diet                    124 non-null    str
 36  ideal_diet_coded              125 non-null    int64
 37  income                        124 non-null    float64
 38  indian_food                   125 non-null    int64
 39  italian_food                  125 non-null    int64
 40  life_rewarding                124 non-null    float64
 41  marital_status                124 non-null    float64
 42  meals_dinner_friend           122 non-null    str
 43  mother_education              122 non-null    float64
 44  mother_profession             123 non-null    str
 45  nutritional_check             125 non-null    int64
 46  on_off_campus                 124 non-null    float64
 47  parents_cook                  125 non-null    int64
 48  pay_meal_out                  125 non-null    int64
 49  persian_food                  124 non-null    float64
 50  self_perception_weight        124 non-null    float64
 51  soup                          124 non-null    float64
 52  sports                        123 non-null    float64
 53  thai_food                     125 non-null    int64
 54  tortilla_calories             124 non-null    float64
 55  turkey_calories               125 non-null    int64
 56  type_sports                   99 non-null     str
 57  veggies_day                   125 non-null    int64
 58  vitamins                      125 non-null    int64
 59  waffle_calories               125 non-null    int64
 60  weight                        123 non-null    str
dtypes: float64(20), int64(27), str(14)
memory usage: 59.7 KB

### Clean the Data

Perhaps we’d like to know more another day, but the team is really interested in just the relationship between calories (`calories_day`) and weight. …and maybe gender.

Can you remove the other columns?

In [174]:
# Remove ‘em.
df_calorie_info = df_food[['calories_day','weight','Gender']].copy()
df_calorie_info.head()

   calories_day                    weight  Gender
0           NaN                       187       2
1           3.0                       155       1
2           4.0  I'm not answering this.        1
3           3.0             Not sure, 240       1
4           2.0                       190       1

What about `NaN`s? How many are there?

In [175]:
# Count ‘em.
df_calorie_info.isna().value_counts().sum()

np.int64(125)

We gotta remove those `NaN`s―the entire row.

In [176]:
# Drop ‘em.
df_calorie_info = df_calorie_info.dropna()

But what about the weird non-numeric values in the column obviously meant for numeric data?

Notice the data type of that column from when you got the types of all the columns?

If only we could convert the column to a numeric type and drop the rows with invalid values. 🤔

In [177]:
# Fix that.
cols = ['calories_day','weight','Gender']
df_calorie_info[cols] = df_calorie_info[cols].apply(pd.to_numeric, errors='coerce')

Now this data seems reasonably clean for our purposes! 😁

Let’s save it somewhere to be shipped off to another teammate. 💾

In [210]:
# Savey save!
save_as = '../data/calories_info.csv'
df_calorie_info.to_csv(save_as, index=False)
with open(save_as, 'rt') as text_file:
    for line in text_file.readlines():
        print(line)

calories_day,weight,Gender

3.0,155.0,1

4.0,,1

3.0,,1

2.0,190.0,1

3.0,190.0,1

3.0,180.0,2

3.0,137.0,1

3.0,125.0,1

3.0,116.0,1

4.0,110.0,1

3.0,264.0,2

3.0,123.0,1

3.0,185.0,2

3.0,145.0,1

3.0,170.0,2

3.0,135.0,1

2.0,165.0,2

3.0,175.0,2

3.0,195.0,2

3.0,185.0,2

3.0,185.0,2

2.0,105.0,1

3.0,125.0,1

2.0,160.0,2

4.0,175.0,2

2.0,180.0,2

2.0,167.0,2

3.0,115.0,1

3.0,205.0,2

3.0,128.0,1

3.0,150.0,1

2.0,150.0,1

3.0,150.0,1

4.0,170.0,1

3.0,150.0,1

3.0,140.0,2

4.0,120.0,1

3.0,135.0,1

2.0,100.0,1

4.0,170.0,1

3.0,113.0,1

2.0,168.0,2

3.0,150.0,2

3.0,169.0,2

4.0,185.0,2

4.0,200.0,2

3.0,165.0,2

2.0,192.0,1

4.0,175.0,2

4.0,140.0,1

3.0,155.0,1

4.0,135.0,1

2.0,118.0,1

4.0,210.0,2

4.0,180.0,1

3.0,140.0,1

3.0,125.0,1

2.0,,1

3.0,145.0,1

4.0,130.0,1

3.0,140.0,1

3.0,140.0,2

4.0,200.0,2

3.0,120.0,1

3.0,150.0,1

2.0,200.0,2

3.0,135.0,1

3.0,145.0,2

2.0,130.0,1

3.0,190.0,1

3.0,127.0,1

3.0,167.0,1

3.0,140.0,1

3.0,190.0,1

3.0,155.0,2

4.0,175.0,2

3.0,129.0,1

4.0,260.0,2

2.0,135.0,1

3.0,175.0,2

3.0,210.0,2

3.0,155.0,1

3.0,185.0,2

4.0,165.0,1

3.0,125.0,1

4.0,135.0,1

3.0,130.0,1

3.0,230.0,1

3.0,125.0,1

3.0,130.0,1

3.0,165.0,1

2.0,128.0,1

3.0,200.0,1

3.0,160.0,1

2.0,170.0,2

4.0,129.0,1

2.0,170.0,1

3.0,138.0,2

4.0,150.0,2

3.0,140.0,1

3.0,185.0,2

4.0,156.0,1

2.0,180.0,1

4.0,135.0,2

## Ask a Manager Salary Survey 2021 (Responses) Data Set

### Load the Data

In [195]:
# Load the Ask A Manager Salary Survey 2021 (Responses) data set into a variable (e.g., df_salary).
df_salaries = pd.read_csv('../data/Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv',sep = '\t')

Was that hard? 🙃

#### rename the file to something that is better for all systems.  
* No spaces in filename (can use '_')
* all lower case

### Explore

You know the drill.

How much data did you just load?

In [196]:
# Count by hand. I’m dead serious.

len(df_salaries)

28062

What are the columns and their types?

In [197]:
# Show the column names and their types.
df_salaries.dtypes

Timestamp                                                                                                                                                                                                                                   str
How old are you?                                                                                                                                                                                                                            str
What industry do you work in?                                                                                                                                                                                                               str
Job title                                                                                                                                                                                                                                   str
If your job title needs additional context, please clarify here:                                                                                                                                                                            str
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)        str
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                          float64
Please indicate the currency                                                                                                                                                                                                                str
If "Other," please indicate the currency here:                                                                                                                                                                                              str
If your income needs additional context, please provide it here:                                                                                                                                                                            str
What country do you work in?                                                                                                                                                                                                                str
If you're in the U.S., what state do you work in?                                                                                                                                                                                           str
What city do you work in?                                                                                                                                                                                                                   str
How many years of professional work experience do you have overall?                                                                                                                                                                         str
How many years of professional work experience do you have in your field?                                                                                                                                                                   str
What is your highest level of education completed?                                                                                                                                                                                          str
What is your gender?                                                                                                                                                                                                                        str
What is your race? (Choose all that apply.)                                                                                                                                                                                                 str
dtype: object

Oh… Ugh! Give these columns easier names to work with first. 🙄

In [198]:
# Rename ‘em.
# Non-binding suggestions: timestamp, age, industry, title, title_context, salary, additional_compensation, currency, other_currency, salary_context, country, state, city, total_yoe, field_yoe, highest_education_completed	gender, race
df_salaries.columns = ['timestamp',
                        'age',
                        'industry',
                          'title', 
                          'title_context', 
                          'salary', 
                          'additional_compensation', 
                          'currency', 
                          'other_currency', 
                          'salary_context', 
                          'country', 
                          'state', 
                          'city', 
                          'total_yoe', 'field_yoe', 
                          'highest_education_completed', 
                          'gender', 
                          'race']
df_salaries

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,"55,000",0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,"34,000",NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,"62,000",3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,"60,000",7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28057,7/12/2024 22:52:01,35-44,Health care,Veterinarian,NaN,135000,NaN,USD,NaN,NaN,United States,Missouri,Wentzville,11 - 20 years,11 - 20 years,"Professional degree (MD, JD, etc.)",Woman,White
28058,7/23/2024 17:51:03,25-34,Computing or Tech,Systems Architect,NaN,109000,NaN,USD,NaN,NaN,USA,Georgia,Atlanta,5-7 years,5-7 years,College degree,Man,White
28059,7/24/2024 12:22:58,18-24,"Accounting, Banking & Finance",Risk Management Associate,NaN,1200,0.0,USD,NaN,NaN,Myanmar,Colorado,Yangon,2 - 4 years,2 - 4 years,Some college,Man,Asian or Asian American
28060,7/26/2024 11:20:45,18-24,Computing or Tech,IT,NaN,1700,10.0,USD,NaN,NaN,Burma,NaN,Yangon,2 - 4 years,1 year or less,Some college,Man,Asian or Asian American
28061,8/20/2024 1:06:13,25-34,Health care,Clinical physiologist,NaN,1200000,NaN,Other,NGN,NaN,Nigeria,NaN,Lagos,2 - 4 years,2 - 4 years,College degree,Woman,Black or African American

It’s a lot, and that should not have been easy. 😏

You’re going to have a gander at the computing/tech subset first because thats *your* industry. But first, what value corresponds to that `industry`?

In [199]:
# List the unique industries and a count of their instances.
df_salaries['industry'].value_counts()

industry
Computing or Tech                               4699
Education (Higher Education)                    2464
Nonprofits                                      2419
Health care                                     1896
Government and Public Administration            1889
                                                ...
Undergrad student                                  1
Concrete Construction                              1
I'm currently a student and don't have a job       1
Student                                            1
Wine & Spirits                                     1
Name: count, Length: 1219, dtype: int64

That value among the top 5 is what you’re looking for innit? Filter out all the rows not in that industry and save it into a new dataframe.

In [200]:
# Filtery filter. (Save it to a new variable, df_salary_tech.)

df_salary_tech = df_salaries[df_salaries['industry'] == 'Computing or Tech'].copy()

Do a sanity check to make sure that the only values you kept are the one you are filtered for.

In [201]:
# Sanity Check 

df_salary_tech['industry'].value_counts()

industry
Computing or Tech    4699
Name: count, dtype: int64

We are very interested in salary figures. But how many dollars 💵 is a euro 💶 or a pound 💷? That sounds like a problem for another day. 🫠

For now, let’s just look at U.S. dollars (`'USD'`).

In [202]:
# Filtery filter for just the jobs that pay in USD!
df_salary_usd = df_salary_tech[df_salary_tech['currency'] == 'USD'].copy()
df_salary_usd['currency'].value_counts()

currency
USD    3777
Name: count, dtype: int64

What we really want know is how each U.S. city pays in tech. What value in `country` represents the United States of America?

In [203]:
# We did filter for USD, so if we do a count of each unique country in descending count order, the relevant value(s) should show up at the top.
df_salary_usd['country'].value_counts()

country
United States               1576
USA                         1222
US                           412
U.S.                         108
United States of America      90
                            ...
Ghana                          1
Nigeria                        1
ss                             1
Nigeria                        1
Burma                          1
Name: count, Length: 76, dtype: int64

### Clean the Data

Well, we can’t get our answers with what we currently have, so you’ll have to make some changes.

Let’s not worry about anything below the first 5 values for now. Convert the top 5 to a single canonical value―say, `'US'`, which is nice and short.

In [204]:
# Replace them all with 'US'.

df_salary_usd['country'] = df_salary_usd['country'].replace(['United States','USA','U.S.','United States of America'],'US')

df_salary_usd.head()

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
8,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,"112,000",10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
43,4/27/2021 11:04:04,25-34,Computing or Tech,Principal Software Engineer,NaN,"187,500",5000.0,USD,NaN,NaN,US,Pennsylvania,Pittsburgh,8 - 10 years,5-7 years,College degree,Woman,White
44,4/27/2021 11:04:04,25-34,Computing or Tech,Intelligence Analyst,NaN,"110,000",20000.0,USD,NaN,"Around 20,000 a year in stock",US,Virginia,"Arlington, VA",8 - 10 years,8 - 10 years,Master's degree,Man,White
46,4/27/2021 11:04:07,35-44,Computing or Tech,Mobile developer,NaN,"144,600",2500.0,USD,NaN,NaN,US,Massachusetts,Boston,5-7 years,5-7 years,PhD,Woman,White
47,4/27/2021 11:04:09,35-44,Computing or Tech,Product Design Director,NaN,"200,850",40000.0,USD,NaN,NaN,US,North Carolina,Chapel Hill,11 - 20 years,11 - 20 years,College degree,Woman,White

Have a look at the count of each unique country again now.

In [205]:
# Count again.
df_salary_usd['country'].value_counts()

country
US                3408
United States       68
Usa                 59
USA                 56
usa                 28
                  ...
Ghana                1
Nigeria              1
ss                   1
Nigeria              1
Burma                1
Name: count, Length: 72, dtype: int64

Did you notice anything interesting?

In [ ]:
# BONUS CREDIT: resolve [most of] those anomalous cases too without exhaustively taking every variant literally into account.

In [ ]:

# BONUS CREDIT: if you’ve resolved it, let’s see how well you did by counting the number of instances of each unique value.

It’s looking good so far. Let’s find out the minimum, mean, and maximum (in that order) salary by state, sorted by the mean in descending order.

In [206]:
# Find the minimum, mean, and maximum salary in USD by U.S. state.
#oh no! :(
df_salary_usd_us = df_salary_usd[df_salary_usd['country'] == 'US'].copy()
salary_stats = (
    df_salary_usd_us
    .groupby('state')['salary']
    .agg(['min','mean','max'])
    .sort_values(by='max', ascending=False)
    )

TypeError: dtype 'str' does not support operation 'mean'

Well, pooh! We forgot that `salary` isn’t numeric. Something wrong must be fixed.

In [207]:
# Fix it.

df_salary_usd_us = df_salary_usd[df_salary_usd['country'] == 'US'].copy()

df_salary_usd_us['salary'] = (
    df_salary_usd_us['salary']
    .astype(str)
    .str.replace(r'[^\d.]','',regex=True)
)

df_salary_usd_us['salary'] = pd.to_numeric(df_salary_usd_us['salary'], errors='coerce')

Let’s try that again.

In [208]:
# Try it again. Yeah!
salary_stats = (
    df_salary_usd_us
    .groupby('state')['salary']
    .agg(['min','mean','max'])
    .sort_values(by='mean', ascending=False)
    )
salary_stats

                                  min           mean      max
state
California, Oregon             200000  200000.000000   200000
California, Colorado           176000  176000.000000   176000
Florida                         28800  160155.204082  2600000
California                          0  156001.126230   875000
Alabama, District of Columbia  156000  156000.000000   156000
...                               ...            ...      ...
Arkansas                        55000   81682.300000   144000
California, Maryland            81500   81500.000000    81500
Louisiana                       35360   79884.444444   110000
Alabama                         29120   74457.777778   120000
Alabama, Montana                72000   72000.000000    72000

[63 rows x 3 columns]

That did the trick! Now let’s narrow this to data 2021 and 2022 just because (lel). *(Hint: that timestamp column may not be a temporal type right now.)*

In [209]:
# Filter the data to within 2021, 2022, or 2023, saving the DataFrame to a new variable, and generate the summary again.



df_salary_usd_us['timestamp'] = pd.to_datetime(df_salary_usd_us['timestamp'], errors='coerce')

selected_years = [2021,2022,2023]

df_salary_year = df_salary_usd_us[df_salary_usd_us['timestamp'].dt.year.isin(selected_years)]


summary_statistics = (df_salary_year
                      .groupby('state')['salary']
                      .agg( ['min','mean','max'])
                      .sort_values('mean',ascending=False)
                      )

summary_statistics

                                  min           mean     max
state
California, Oregon             200000  200000.000000  200000
California, Colorado           176000  176000.000000  176000
California                          0  156142.343186  875000
Alabama, District of Columbia  156000  156000.000000  156000
Washington                         72  150749.409524  950000
...                               ...            ...     ...
Arkansas                        55000   81682.300000  144000
California, Maryland            81500   81500.000000   81500
Louisiana                       35360   79884.444444  110000
Alabama                         29120   74457.777778  120000
Alabama, Montana                72000   72000.000000   72000

[63 rows x 3 columns]

## Bonus

Clearly, we do not have enough data to produce useful figures for the level of specificity you’ve now reached. What do you notice about Delaware and West Virginia?

Let’s back out a bit and return to `df_salary` (which was the loaded data with renamed columns but *sans* filtering).

### Bonus #0

Apply the same steps as before to `df_salary`, but do not filter for any specific industry. Do perform the other data cleaning stuff, and get to a point where you can generate the minimum, mean, and maximum by state.

### Bonus #1

This time, format the table output nicely (*$12,345.00*) without modifying the values in the `DataFrame`. That is, `df_salary` should be identical before versus after running your code.

(*Hint: if you run into an error about `jinja2` perhaps you need to `pip install` something.*)

### Bonus #2

Filter out the non-single-states (e.g., `'California, Colorado'`) in the most elegant way possible (i.e., *not* by blacklisting all the bad values).

### Bonus #3

Show the quantiles instead of just minimum, mean, and maximum―say 0%, 5%, 25%, 50%, 75%, 95%, and 100%. Outliers may be deceiving.

Sort by whatever interests you―like say the *50th* percentile.

And throw in a count by state too. It would be interesting to know how many data points contribute to the figures for each state. (*Hint: your nice formatting from Bonus #1 might not work this time around.* 😜)